"""Regulatory compliance - China, EU AI Act configurable guardrails."""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from typing import Any

from learnbot_mcp.config import get_settings

log = logging.getLogger(__name__)


def disclosure_message() -> str:
    """Return the transparency disclosure based on regulatory regime."""
    cfg = get_settings()
    regime = cfg.regulatory_regime.lower()
    if regime == "china":
        return "Real-name verification is required for continued use."
    if regime == "eu":
        return "Responses are generated by AI. This conversation is logged."
    return ""


def requires_real_name_auth() -> bool:
    cfg = get_settings()
    if cfg.regulatory_regime.lower() == "china":
        return True
    return cfg.real_name_auth


def retention_limit() -> timedelta:
    cfg = get_settings()
    return timedelta(days=cfg.conversation_retention_days)


def refusal_templates() -> dict[str, str]:
    """Return topic refusal templates per regime."""
    base = {
        "politics": "I cannot discuss political topics.",
        "gore": "I cannot generate content depicting violence or gore.",
        "personal_info": "I cannot request or store personal information.",
    }
    cfg = get_settings()
    if cfg.regulatory_regime.lower() == "china":
        base.update(
            {
                "politics": "I am unable to discuss political topics as per content guidelines.",
                "religion": "I cannot discuss religious topics.",
                "historical_figures": "I cannot comment on historical political figures.",
            }
        )
    if cfg.regulatory_regime.lower() == "eu":
        base.update(
            {
                "medical_advice": "I cannot provide medical advice. Consult a professional.",
                "financial_advice": "I cannot provide financial advice. Consult a professional.",
            }
        )
    return base


async def check_conversation_retention() -> dict[str, Any]:
    """Delete conversations older than the retention limit. Returns count removed."""
    cfg = get_settings()
    if cfg.regulatory_regime.lower() == "none":
        return {"success": True, "deleted": 0, "note": "No retention policy active"}

    from learnbot_mcp.database import get_db

    cutoff = (datetime.now(UTC) - retention_limit()).isoformat()
    async with get_db() as db:
        cur = await db.execute("SELECT id FROM conversations WHERE updated_at < ?", (cutoff,))
        expired = [r["id"] for r in await cur.fetchall()]
        for cid in expired:
            await db.execute("DELETE FROM turns WHERE conversation_id=?", (cid,))
            await db.execute("DELETE FROM conversations WHERE id=?", (cid,))
        await db.commit()
    if expired:
        log.info("Retention cleanup: deleted %d old conversations", len(expired))
    return {"success": True, "deleted": len(expired)}
